os: linux
dist: bionic
language: generic

services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_af164d12e359_key -iv $encrypted_af164d12e359_iv -in service-account.json.enc -out service-account.json -d
  - curl --silent --fail https://sdk.cloud.google.com | bash >/dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-289814
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PSW" | docker login -u "$DOCKER_USR" --password-stdin

script:
  - docker build -t client:dev -f ./client/Dockerfile.dev ./client
  - docker run -e CI=true client:dev npm test
